;this is emacs config file on windows7, emacs 22.3 for windows
;the config file dir is "c:\user\Administrator\AppData\Roaming\_emacs"
; if the admin is jusss,and no administrator, it will be  C:\Users\jusss\AppData\Roaming\_emacs

(set-default-font "-outline-ÐÂËÎÌå-normal-r-normal-normal-13-97-96-96-c-*-iso8859-1")

(setq load-path(cons "d:/emacs-config-jusss" load-path))

(load "start-up.el")

(load "erc-ssl.el")

(load "ido-mode.el")

(load "set-mark-hot-key.el")

(load "set-default-directory.el")

(load "high-light")

(load "chez-scheme.el")

(load "file-coding.el")
