#!/usr/bin/env python3
import os

cons=lambda x,y:[x]+y
car=lambda x:x[0]
cdr=lambda x:x[1:]

def filter_list(list1,list2,key):
    if list1==[]:
        return list2
    else:
        if key==car(list1):
            return reverse_list(filter_list(cdr(list1),list2,key),[])
        else:
            return reverse_list(filter_list(cdr(list1),cons(car(list1),list2),key),[])

def reverse_list(list1,list2):
    if list1==[]:
        return list2
    else:
        return reverse_list(cdr(list1),cons(car(list1),list2))

def match_list(element,list):
    if list == []:
        return 0
    elif element == car(list):
        return 1
    return match_list(element,cdr(list))

def rename_files(count,list):
    if list ==[]:
        return 0
    else:
        if count<10:
            str_count='0'+str(count)
        else:
            str_count=str(count)
        if 'rename_files' == car(list):
            return rename_files(count,cdr(list))
        else:
            if match_list(str_count,list) == 0:
                cmd = 'mv ' + dir_name + car(list) + ' ' + dir_name + str_count
                os.system(cmd)
                return rename_files(count+1,cdr(list))
            else:
                return rename_files(count+1,filter_list(list,[],str_count))

dir_name = os.getcwd() + '/'
file_list = os.listdir(dir_name)
count = 1
rename_files(count,file_list)
